# 工作流程的名稱
name: Deploy Blazor WASM to GitHub Pages

# 觸發條件：當推送到 main 或 master 分支時執行
on:
  push:
    branches: [ main, master ]

# 工作內容
jobs:
  build-and-deploy:
    # 執行此工作的虛擬機器環境
    runs-on: ubuntu-latest

    steps:
      # 步驟 1: 抓取你的程式碼
      - name: Checkout
        uses: actions/checkout@v3

      # 步驟 2: 安裝 .NET 8 SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 步驟 3: 發佈 .NET 專案
      # 我們將所有發佈產物都放到一個名為 'publish' 的資料夾中
      - name: Publish .NET Project
        run: dotnet publish Blazor_from/Blazor_from.csproj -c Release -o publish --nologo

      # 步驟 4: 【偵錯】列出 publish 資料夾的內容
      # 這是關鍵的驗證步驟，讓我們看看 dotnet publish 到底生成了什麼
      - name: List publish directory contents
        run: ls -R publish

      # 步驟 5: 修改 base href
      # 我們現在直接在 'publish/wwwroot/index.html' 這個確定存在的位置進行修改
      - name: Change base-tag in index.html
        run: sed -i 's/<base href="\/" \/>/<base href="\/Blazor_from\/" \/>/g' publish/wwwroot/index.html

      # 步驟 6: 部署整個 publish/wwwroot 資料夾
      # 既然 dotnet publish 已經幫我們把所有東西都放好了，我們就直接部署這個資料夾
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # 部署到 gh-pages 分支
          folder: publish/wwwroot # 從這個資料夾部署

